# Generated by Django 4.1.7 on 2023-05-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reportingmanager'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='zone',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('South', 'South'), ('North', 'North')], max_length=6, null=True),
        ),
    ]
