# Generated by Django 4.1.7 on 2023-05-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_salesrepresentative_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='reporting_business_unit',
            field=models.CharField(blank=True, choices=[('OTC', 'OTC'), ('IVD', 'IVD'), ('HTP', 'HTP')], max_length=10, null=True),
        ),
    ]
