# Generated by Django 4.1.7 on 2023-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_doctor_clinic_registration_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='drug_license_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
