# Generated by Django 4.1.7 on 2023-04-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_pharmacy_drug_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.distributor'),
        ),
    ]
