# Generated by Django 4.1.7 on 2023-04-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_working_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.distributor'),
        ),
    ]
