# Generated by Django 4.1.7 on 2023-04-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_order_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.distributor'),
        ),
    ]
