# Generated by Django 4.1.7 on 2023-04-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_working_distributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock',
            new_name='pack_size',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
