# Generated by Django 4.1.7 on 2023-05-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_working_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('working', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geotag', to='api.working')),
            ],
        ),
    ]
